arch:
- aarch64
- amd64
- armhf
- armv7
- i386
description: A basic implementation of dnsCrypt
image: linickx/addon-dnscrypt-proxy-{arch}
init: false
map:
- addon_config:rw
name: dnsCrypt Proxy
ports:
  53/tcp: 53
  53/udp: 53
slug: dnscrypt-proxy
url: https://github.com/linickx/addon-dnscrypt-proxy
version: 2025.10.15
